# Generated by Django 4.2.16 on 2025-01-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
