# Generated by Django 5.1.6 on 2025-02-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transaction_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='accountNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
