# Generated by Django 4.2.16 on 2025-01-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
