# Generated by Django 4.2.16 on 2025-01-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='last_blood_donate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
