# Generated by Django 4.2.16 on 2025-01-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_remove_people_last_blood_donate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='available_for_donate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='last_blood_donate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
