# Generated by Django 4.2.16 on 2025-01-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood',
            name='available_for_donate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
